#!/usr/bin/env bash

set -xe

while : ; do
    CPU_USAGE=`top -bn 2 -d 5 | grep '^%Cpu' | tail -n +2 | awk '{print $2+$4+$6}'`
    if [ 1 -eq `echo "$CPU_USAGE < 7.5" | bc` ]; then
        break
    fi
done
